---
title: 'Peer-graded Assignment: R Markdown and Leaflet'
author: "Swati"
date: '2022-04-03'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Create a web page using R Markdown that features a map created with Leaflet.

Problem Description

Host your webpage on either GitHub Pages, RPubs, or NeoCities.

Your webpage must contain the date that you created the document, and it must contain a map created with Leaflet. We would love to see you show off your creativity!

Using required Packages
library(leaflet)
## Warning: package 'leaflet' was built under R version 3.4.4
library(htmltools)
## Warning: package 'htmltools' was built under R version 3.4.4
Accessing the data from .csv text file
From Kagle: Dataset about the best restaurants in the world. By Megh Mayur. Contains the list of The World’s 50 Best Restaurants for 2018 (https://www.kaggle.com/mmayur/the-worlds-50-best-restaurants)

setwd("c:/users/swati/Documents/datasets/")
datamap <- read.csv(file = "TheWorlds50BestRestaurants2018.csv", header = TRUE, sep = ",")
Creating my data frame in order to manipulate the dataset like a table.

mimapa <- data.frame(Ranking = datamap$Ranking,
                     Name = datamap$Name,
                     City = datamap$City,
                     Country = datamap$Country,
                     Latitude = datamap$Latitude,
                     Longitude = datamap$Longitude
                     )
Activating the Map
map <- mimapa %>%
  leaflet() %>%
  addTiles() %>%
  addMarkers(popup=paste
             ("<br>Country: ", 
               htmlEscape(mimapa$Country), 
              "<br>City: ", 
               htmlEscape(mimapa$City), 
              "<br>Restaurant: ", 
               htmlEscape(mimapa$Name),
              "<br>Ranking: ",
               formatC(datamap$Ranking, format = "d", big.mark = ",")
              ) 
            )
## Assuming "Longitude" and "Latitude" are longitude and latitude, respectively
map
